# Copy this file to config.yml and adjust
config:
    # The base directory of the file browser
    root: public/testwebroot/
    # The relative web path that points to the same directory as root
    # Can be ignored if not displaying webpages
    webroot: /testwebroot/
    webpageIndexFiles:
        - index.html
        - index.php
    directories:
        /:
            display:
                webpages: true
                directories: true
                files: true
            blacklist:
                webpages: []
                directories: []
                files: []
                all: []
            whitelist:
                webpages: []
                directories: []
                files: []
            recursive: true
            description: "Description"
        asdf/foo/:
            blacklist:
                all:
                - genericblacklist2
            recursive: true
        asdf/foo/bar/:
            display:
                files: true
            blacklist:
                webpages:
                - webpage3
            description: "Derp."
