# Copy this file to config.yml and adjust
config:
    # The base directory of the file browser, can be a path relative to the project or an absolute path
    root: public/
    # The relative web path that points to the same directory as root
    webroot: /
    # Name of the stylesheet to use
    theme: dark
    title: "Viller's web file browser"
    # A webpage directory must have at least one of these files present in order to be shown
    indexFiles:
        - index.html
        - index.php
    directories:
        /:
            display:
                webpages: true
                directories: true
                files: true
            blacklist:
                webpages: []
                directories: []
                files: []
                all: []
            whitelist:
                webpages: []
                directories: []
                files: []
            recursive: true
            description: ""
